# fly.toml app configuration file generated for travel-blog on 2024-04-16T21:35:34-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'travel-blog'
primary_region = 'ord'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1


# I'm not strictly sure that this is necessary to run the prisma studio
[[services]]
internal_port = 5555
protocol = "tcp"
processes = ["app"]

[[services.ports]]
handlers = ["tls", "http"]
port = 5555
