import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from '@/lib/utils';

import Link from 'next/link';
import { getServerSession } from 'next-auth';
import NavMenu from '@/components/top-navigation';
import { ClerkProvider } from '@clerk/nextjs'
import React from 'react';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout (props: {
  children: React.ReactNode;
  modal: React.ReactNode;

}
) {

  return (
        <ClerkProvider>

    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background border border-black  flex flex-col   min-w-full w-full antialiased",
         inter.className
      ) }>
     <NavMenu />
<main className="flex flex-col flex-grow items-center border-2 border-teal-400 p-1 md:p-5">
            { props.children }
            { props.modal }


          </main>
          <div id="modal-root" />
      </body>
      </html>
      </ClerkProvider>
  );
}
